version: '3.8'


services:
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net

  mysqldb:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: ismayilov10
    ports:
      - "5432:5432"
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup

  app:
    image: "app"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/library
      - spring.datasource.username=root
      - spring.datasource.password=ismayilov10
#      - spring.jpa.hibernate.ddl-auto=update
      - SERVER_PORT=8082
      - spring.redis.host=redis
      - spring.redis.post=6379
    restart: always
    networks:
      - shared-net


networks:
  shared-net:
    driver: bridge




